## ORACLE ULIMIT SETTINGS:

addgroup --system dba
adduser --system --ingroup docker --disabled-password --home=/home/oracle --shell /bin/bash oracle
adduser oracle dba

SECURITY_DOCKER_DIR=/etc/security/limits.d
ORA_SECURITY_CONF=$SECURITY_DOCKER_DIR/oracle.conf

mkdir -p $SECURITY_DOCKER_DIR
rm $ORA_SECURITY_CONF

cat <<EOF >> $ORA_SECURITY_CONF
oracle          soft    nproc           2047
oracle          hard    nproc           16384
oracle          soft    nofile          1024
oracle          hard    nofile          65536

EOF

## ORACLE SYSCTL SETTINGS:

SYSCTL_DOCKER_DIR=/etc/sysctl.d
ORA_SYSCTL_CONF=$SYSCTL_DOCKER_DIR/60-oracle.conf

mkdir -p $SYSCTL_DOCKER_DIR
rm $ORA_SYSCTL_CONF

cat <<EOF >> $ORA_SYSCTL_CONF
fs.file-max = 65536
fs.aio-max-nr = 1048576
# semaphores: semmsl, semmns, semopm, semmni
kernel.sem = 250 32000 100 128
# (Oracle recommends total machine Ram -1 byte)
kernel.shmmax = 2147483648
kernel.shmall = 2097152
kernel.shmmni = 4096
net.ipv4.ip_local_port_range = 1024 65000
# 999 is the gid for docker
vm.hugetlb_shm_group = 999
vm.nr_hugepages = 64

EOF

sysctl -p $ORA_SYSCTL_CONF

exit 0

## DOCKER SETTINGS

SYSTEMD_DOCKER_DIR=/etc/systemd/system/docker.service.d
ORA_DOCKER_CONF=$SYSTEMD_DOCKER_DIR/oracle.conf

#mkdir -p $SYSTEMD_DOCKER_DIR
rm $ORA_DOCKER_CONF
cat <<EOF >> $ORA_DOCKER_CONF
# This file may be automatically generated by an installation program.
# By default, Docker uses a loopback-mounted sparse file in
# /var/lib/docker. The loopback makes it slower, and there are some
# restrictive defaults, such as 100GB max storage.

# If your installation did not set a custom storage for Docker, you
# may do it below.

# Example: Use a custom pai# r of raw logical volumes (one for metadata,
# o# (ne for data).
# Environment="DOCKER_STORAGE_OPTIONS= \\
# --storage-opt dm.metadatadev=/data1/docker/my-docker-metadata \\
# --storage-optdm.datadev=/data1/docker/my-docker-data \\
# --storage-opt dm.basesize=15G"
[Service]
Environment="DOCKER_STORAGE_OPTIONS=\\
--storage-opt dm.basesize=15G"

EOF

cat $ORA_DOCKER_CONF

systemctl daemon-reload
systemctl show --property=Environment docker
systemctl restart docker

